[package]
name = "zenith_topo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zenith_math = { path = "../zenith_math" }
zenith_geom = { path = "../zenith_geom" }
nalgebra.workspace = true
thiserror.workspace = true
serde.workspace = true
approx.workspace = true
log.workspace = true
