[package]
name = "zenith_algo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zenith_math = { path = "../zenith_math" }
zenith_geom = { path = "../zenith_geom" }
zenith_topo = { path = "../zenith_topo" }
zenith_tess = { path = "../zenith_tess" }
nalgebra.workspace = true
thiserror.workspace = true
serde.workspace = true
approx.workspace = true
log.workspace = true

[dev-dependencies]
zenith_io = { path = "../zenith_io" }

[dev-dependencies.serde_json]
workspace = true
