pub mod bspline_basis;
pub mod coons_patch;
pub mod curvature;
pub mod curve;
pub mod extremum;
pub mod gordon_surface;
pub mod nurbs_curve;
pub mod nurbs_curve_2d;
pub mod nurbs_surface;
pub mod offset;
pub mod ssi;
pub mod ssi_march;
pub mod surface;
pub mod surface_blend;
pub mod triangular_patch;
pub mod trimmed_surface;

pub use bspline_basis::KnotVector;
pub use coons_patch::CoonsPatch3;
pub use curvature::SurfaceCurvature;
pub use curve::{Circle3, Curve3, Line3};
pub use extremum::{ExtremumEngine, PointCurveProjection, PointSurfaceProjection};
pub use gordon_surface::GordonSurface3;
pub use nurbs_curve::{ControlPoint3, NurbsCurve3};
pub use nurbs_curve_2d::{ControlPoint2, NurbsCurve2};
pub use nurbs_surface::NurbsSurface3;
pub use offset::OffsetEngine;
pub use ssi::{SurfaceIntersection, SurfaceIntersectionPoint};
pub use ssi_march::{IntersectionMarcher, MarchedIntersection};
pub use surface::{PlaneSurface3, Surface3};
pub use surface_blend::SurfaceBlend3;
pub use triangular_patch::TriangularPatch3;
pub use trimmed_surface::{TrimLoop2D, TrimmedSurface3};
